use super::macros::enum_builder;
enum_builder! {
    :"A Mission Type in Warframe"
    MissionType;
    AncientRetribution = "Ancient Retribution",
    Arena,
    Assassination,
    Assault,
    Capture,
    Conclave,
    DarkSectorDefection = "Dark Sector Defection",
    DarkSectorDefense = "Dark Sector Defense",
    DarkSectorDisruption = "Dark Sector Disruption",
    DarkSectorExcavation = "Dark Sector Excavation",
    DarkSectorSabotage = "Dark Sector Sabotage",
    DarkSectorSurvival = "Dark Sector Survival",
    Defense,
    Disruption,
    Excavation,
    ExterminationArchwing = "Extermination (Archwing)",
    Extermination,
    FreeRoam = "Free Roam",
    Hijack,
    Hive,
    HiveSabotage = "Hive Sabotage",
    Interception,
    InterceptionArchwing = "Interception (Archwing)",
    MobileDefense = "Mobile Defense",
    MobileDefenseArchwing = "Mobile Defense (Archwing)",
    OrokinSabotage = "Orokin Sabotage",
    Orphix,
    PursuitArchwing = "Pursuit (Archwing)",
    Relay,
    Rescue,
    RushArchwing = "Rush (Archwing)",
    Sabotage,
    SabotageArchwing = "Sabotage (Archwing)",
    Skirmish,
    Spy,
    Survival,
    Volatile,
    Alchemy,
    Corruption,
    VoidCascade = "Void Cascade",
    Defection
}
