use super::macros::enum_builder;

enum_builder! {
    RewardType;
    Vauban = "vauban",
    Vandal = "vandal",
    Wraith = "wraith",
    Skin = "skin",
    Helmet = "helmet",
    Nitain = "nitain",
    Mutalist = "mutalist",
    Weapon = "weapon",
    Fieldron = "fieldron",
    Detonite = "detonite",
    Mutagen = "mutagen",
    Aura = "aura",
    NeuralSensors = "neuralSensors",
    OrokinCell = "orokinCell",
    AlloyPlate = "alloyPlate",
    Circuits = "circuits",
    ControlModule = "controlModule",
    Ferrite = "ferrite",
    Gallium = "gallium",
    Morphics = "morphics",
    NanoSpores = "nanoSpores",
    Oxium = "oxium",
    Rubedo = "rubedo",
    Salvage = "salvage",
    Plastids = "plastids",
    PolymerBundle = "polymerBundle",
    ArgonCrystal = "argonCrystal",
    Cryotic = "cryotic",
    Tellurium = "tellurium",
    Neurodes = "neurodes",
    Nightmare = "nightmare",
    Endo = "endo",
    Reactor = "reactor",
    Catalyst = "catalyst",
    Forma = "forma",
    Synthula = "synthula",
    Exilus = "exilus",
    Riven = "riven",
    KavatGene = "kavatGene",
    KubrowEgg = "kubrowEgg",
    Traces = "traces",
    Other = "other",
    Credits = "credits",
}
